def node_require(script)
  require Pod::Executable.execute_command('node', ['-p', "require.resolve('#{script}', {paths: [process.argv[1]]})", __dir__]).strip
end

# Resolve react_native_pods.rb with node to allow for hoisting
node_require('react-native/scripts/react_native_pods.rb')

# Resolve native-modules with node to allow for hoisting
node_require('@react-native-community/cli-platform-ios/native_modules.rb')

# Resolve react-native-permissions with node to allow for hoisting
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'videoDownloader' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  setup_permissions([
    'Camera',           # 相机权限
    'Microphone',       # 麦克风权限
    'PhotoLibrary',     # 照片权限（访问照片库）
    'LocationWhenInUse' # 位置权限（仅在使用时获取位置）
  ])

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
